name: telegram message
on: 
  issues:
    types: [opened, edited, closed, reopened, assigned]
  pull_request:
    types: [opened, edited, closed, reopened, assigned, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
    send_issue_message:
      name: Send Issue Message
      if: github.event_name == 'issues'
      runs-on: ubuntu-latest
      steps:
        - name: Send Telegram Message for Issue
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            disable_web_page_preview: true
            format: html
            message: |
              Issue event: ${{ github.event_name }} ${{github.event.action}}.
              <b>Title: ${{ github.event.issue.title }}</b>
              <span class="tg-spoiler">Body: ${{ github.event.issue.body }}</span>
              
              URL: ${{ github.event.issue.html_url }}
              
              Assignees: ${{ join(github.event.issue.assignees.*.login, ', ') }}
              
    send_pr_message:
      name: Send PR Message
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
        - name: Send Telegram Message for PR
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              PR Event: ${{ github.event_name }} ${{ github.event.action }}
              Title: ${{ github.event.pull_request.title }}
              Body: ${{ github.event.pull_request.body }}
              
              URL: ${{ github.event.pull_request.html_url }}

              Reviewers: ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}
              
    send_review_message:
      name: Send Review Message
      if: github.event_name == 'pull_request_review'
      runs-on: ubuntu-latest
      steps:
        - name: Send Telegram Message for PR Review
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              PR Review Event: ${{ github.event_name }}
              ${{ github.event.review.html_url }}